### ISSUE TITLE
Fuji RAF support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ebaumann/jphototagger#10]
```
I was trying to use JPT to browse a folder with Fuji RAW files, after adding 
the RAF extension to the user defined file type and changing my thumbnail 
generation to dcraw I was able to browse those folders but I still have some 
issues:

- EXIF metadata isn't shown for RAF files
- Any of the filters (like timeline or keywords) can't "see" those files, even 
if I had the keywords on the file
- The thumbs have a green hue (less important of the 3)


JPT 0.32.16, Ubuntu 13.10





```

Original issue reported on code.google.com by `jpnalme...@gmail.com` on 16 Jan 2014 at 10:25

Attachments:
* [Screenshot from 2014-01-16 10:21:49.png](https://storage.googleapis.com/google-code-attachments/jphototagger/issue-10/comment-0/Screenshot from 2014-01-16 10:21:49.png)
* [Screenshot from 2014-01-16 10:21:41.png](https://storage.googleapis.com/google-code-attachments/jphototagger/issue-10/comment-0/Screenshot from 2014-01-16 10:21:41.png)
* [Screenshot from 2014-01-16 10:22:00.png](https://storage.googleapis.com/google-code-attachments/jphototagger/issue-10/comment-0/Screenshot from 2014-01-16 10:22:00.png)

**Comment by ebaumann** [comment]
The current version of https://github.com/drewnoakes/metadata-extractor does not support the file format - tested with a Fujifilm X-E2 raw file. Maybe in a year or so. Closing the bug due limited spare time.
