### ISSUE TITLE
Text Field Bugs

### ISSUE THREAD

**Issue by sAnideos** [ebaumann/jphototagger#11]
Hello, 

I would like to report some bugs that I've found. These bugs are associated to text fields.

1) The date field: Date 0000-00-00 is considered a valid date. Also it accepts moth number up to 19 (>12) and day number 39 (>31). (Also, it would be nice, if there was a calendar where you can select the date. Maybe I can help with that.)

2) When I try to Cut from a text field by pressing Ctrl+X, it just copies the value.

**Comment by ebaumann** [comment]
The date field in the right "Edit" tab is only a workaround for images without EXIF metadata to be displayed in the left time line.

Zeros are explicitely allowed to tag such images, where you know the year or year/month but not the month/day. 2010-00-00 is an image taken at an unkonwn month/day within the year 2010. Now it's checking against the Gregorian calendar with upcoming version 0.32.22.

I can't figure out, why Ctrl+X does not work (Debugger: in the JDK code, the cut action will be invoked but it does not cut).

**Comment by ebaumann** [comment]
Figured out the Ctrl+X issue and fixed it (commit 583bb47).
