### ISSUE TITLE
Template Name Bug

### ISSUE THREAD

**Issue by sAnideos** [ebaumann/jphototagger#12]
Hello, 

I would like to report some more bugs about the Template Name. Firstly, the space characters at the start and the end of the string are not trimming when saving the name. Also, space can be applied as a valid name. Finally, there is no minimum and maximum characters limit. If the given string is too big the program may crush.

The steps to reproduce the final bug: 1) Select "Save as template", 2) Give a huge string as input and save it, 3) Try to select the template or try to delete. (Of course, no one will give such a big string, but still it is good to deal with the problem).

Also, the album name has no upper bound. A huge string can cause the same problem.

**Comment by ebaumann** [comment]
A huge template name or favorite name  name will not kill the application. Database errors will be reported, but do not kill the app. In the worst case nothing will be saved or the name will be truncated. To my surprise: The template's table definition allows up 256 characters for the name but in my test it did save a name with 300 chars.
