### ISSUE TITLE
Images Layout

### ISSUE THREAD

**Issue by sAnideos** [ebaumann/jphototagger#14]
When hiding/minimizing the right panel of the program, images' screen is not reordered. But it seems that this is a visual problem. Actually, the images have been reordered in the background but the screen has not be refreshed. This causes some empty space. I post some screenshots to make this clearer. 

![image missing](https://cloud.githubusercontent.com/assets/6011300/10018432/5808b5c6-613f-11e5-812c-e0047c6bc0d4.png)
![image missing2](https://cloud.githubusercontent.com/assets/6011300/10018433/580b2a86-613f-11e5-9b1f-34dc6df9b4c3.png)

Steps to reproduce: 1) Minimize right panel (first screenshot), 2) Hover (second screenshot) or click on the empty space (red box). When clicking the screen is refreshed and everything gets back to normal.

**Comment by ebaumann** [comment]
It seems to be system dependent. On my systems Windows and Linux I can't reproduce this. I'm using the Oracle JDK - maybe this is an issue.

If you have Java skills,  you can download the source code. The method org.jphototagger.program.module.thumbnails.ThumbnailsPanel#paintComponent(Graphics g) will be called immediately after minimizing. Insert there a break point. But I can't find an elegant solution for this problem (Ugly: Add an listener to the SplitPane and force repainting - but that interferes with the "JDK way").
