### ISSUE TITLE
Items in the Metadata tab aren't sorted properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ebaumann/jphototagger#9]
```
What steps will reproduce the problem?
1. Open the Miscellaneous tab
2. Expand the tabs


The items in each group arent sorted propely, this is annoying for ISO or Focal 
Length.


JPT 0.32.16, Ubuntu 13.10


Please provide any additional information below.


```

Original issue reported on code.google.com by `jpnalme...@gmail.com` on 16 Jan 2014 at 10:13

Attachments:
* [Screenshot from 2014-01-16 10:08:20.png](https://storage.googleapis.com/google-code-attachments/jphototagger/issue-9/comment-0/Screenshot from 2014-01-16 10:08:20.png)

**Comment by ebaumann** [comment]
Have no time to fix this.
